# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: pr3-pony's magical wonderland
email: 3254tg89@gmail.com
description: 反正就只是個廚站 # this means to ignore newlines until "baseurl:"
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://prprprpony.github.io" # the base hostname & protocol for your site
github_username:  users/prprprpony
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/page:num/"
# Build settings
markdown: kramdown
